name: Release

on:
  push:
    tags:
      - '*'
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          overwrite: true
          fail_on_unmatched_files: true
          files: |
            main.js
            manifest.json
            styles.css
